# Generated by Django 5.0.7 on 2024-09-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regestration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=80)),
            ],
        ),
    ]
