# Generated by Django 5.1.1 on 2024-09-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecap', '0003_alter_regestration_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Regestration',
        ),
    ]
