# Generated by Django 5.1.1 on 2024-10-01 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecap', '0007_product_show_delete_vendor_display'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product_show',
        ),
    ]
