# Generated by Django 5.1.1 on 2024-10-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecap', '0008_delete_product_show'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
