# Generated by Django 5.1.1 on 2024-10-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecap', '0012_vendor_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=255)),
                ('prod_id', models.PositiveIntegerField()),
                ('prod_adate', models.DateField()),
                ('prod_qun', models.PositiveIntegerField()),
                ('prod_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prod_gstp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prod_gstr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tprice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='vendor_show',
        ),
    ]
