# Generated by Django 5.1.1 on 2024-10-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecap', '0014_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
