# Generated by Django 5.1.1 on 2024-10-24 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecap', '0015_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
